# Generated by Django 4.1.1 on 2023-12-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=40)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=3, null=True)),
                ('Data_Bundle', models.CharField(blank=True, choices=[('3_GHS__340.29MB', '3 Ghs  340.29Mb'), ('5_GHS__740MB', '5 Ghs  740Mb'), ('10_GHS__1GB', '10 Ghs  1Gb')], default='', max_length=15)),
                ('show_custom_data_allocator', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
