# Generated by Django 5.0 on 2024-01-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userdb_data_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniWallet_Unifi_Jasmin_Transactions_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Voucher_Code_Recieved', models.BooleanField(auto_created=True, default=False)),
                ('Payment_Status', models.BooleanField(auto_created=True, default=False)),
                ('UniWallet_Transaction_ID', models.CharField(auto_created=True, default='', max_length=15, null=True, unique=True)),
                ('Voucher_Code', models.PositiveIntegerField(auto_created=True, null=True, unique=True)),
                ('Full_Name', models.ForeignKey(default='', max_length=40, on_delete=django.db.models.deletion.CASCADE, to='backend.userdb')),
            ],
        ),
    ]
