# Generated by Django 5.0 on 2024-01-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_uniwallet_unifi_jasmin_transactions_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniwallet_unifi_jasmin_transactions_details',
            old_name='Full_Name',
            new_name='Phone_Number',
        ),
    ]
